name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        id: build_image
        run: |
          docker build -t flask-app:latest . || { echo 'Docker image build failed'; exit 1; }

      - name: Deploy to EC2
        if: steps.build_image.outcome == 'success'
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          printf "%s" "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USERNAME}@${HOST} "
              docker save flask-app:latest | docker load || { echo 'Docker load failed'; exit 1; } &&
              docker-compose up -d
          "
