name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t flask-app .

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }} # Your EC2 instance's public IP or hostname
          USERNAME: ${{ secrets.EC2_USER }} # Your EC2 instance's username (e.g., ec2-user, ubuntu)
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # Your SSH private key
        run: |
          echo "${PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USERNAME}@${HOST} "docker pull <your-dockerhub-username>/flask-app:latest && docker-compose up -d"
