name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Commenting out the pytest part for now
      # - name: Run tests
      #   run: |
      #     pytest

      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "${PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USERNAME}@${HOST} "
            # Ensure Docker is running
            sudo systemctl start docker
            # Optional: Pull the latest image if using Docker Hub
            # docker pull your-dockerhub-username/flask-app:latest
            docker-compose up -d
          "
